sidebar_icons:
  summary: list-check
  technical skills: gear
  employment: person-workspace
  projects: folder
  portfolio: rocket
  education: trophy
  certifications: clipboard-check
  interests: joystick
section_icons:
  experience summary: memo
  technical skills: man_technologist
  employment: office
  projects: open_file_folder
  portfolio: rocket
  education: school
  certifications: trophy
  interests: video_game
colors:
  - '#ffc09f'
  - '#a0ced9'
  - '#95b8d1'
  - '#b8e0d2'
  - '#e8dff5'
  - '#fcf4dd'
  - '#ddedea'
  - '#daeaf6'
  - '#d1cfe2'
  - '#9cadce'
  - '#7ec4cf'
  - '#e69597'
  - '#ceb5b7'
  - '#f6bc66'
  - '#bde0fe'
  - '#8dd3c7'
  - '#ffffb3'
  - '#bebada'
  - '#fb8072'
  - '#80b1d3'
  - '#fdb462'
  - '#b3de69'
  - '#fccde5'
  - '#d9d9d9'
dark_colors:
  - "#2ab7ca"
  - "#fed766"
  - "#dec3c3"
  - "#3da4ab"
  - "#fe8a71"
  - "#d0e1f9"
  - "#c99789"
  - "#96ceb4"
  - "#ffefd7"
  - "#e4dcf1"
  - "#e0ac69"
  - "#abc4ff"
  - "#d1d1d1"
  - "#809bce"
  - "#9cf6f6"
  - "#f08080"
default_color: "#2f4550"
